-- vim.keymap.set("n", "[[", function()
-- 	require("nvim-treesitter.textobjects.move").goto_previous_start("@scope.outer")
-- end)
--
-- vim.keymap.set("n", "]]", function()
-- 	require("nvim-treesitter.textobjects.move").goto_next_start("@scope.outer")
-- end)
--
-- vims.keymap.set("n", "[]", function()
-- 	require("nvim-treesitter.textobjects.move").goto_previous_end("@scope.outer")
-- end)
--
-- vim.keymap.set("n", "][", function()
-- 	require("nvim-treesitter.textobjects.move").goto_next_end("@scope.outer")
-- end) 
